[package]
name = "ntex-mqtt"
version = "0.5.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "MQTT Client/Server framework for v5 and v3.1.1 protocols"
documentation = "https://docs.rs/ntex-mqtt"
repository = "https://github.com/ntex-rs/ntex-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[dependencies]
ntex = "0.2.0"
ntex-router = "0.3.8"
bitflags = "1.2.1"
bytes = "0.5.6"
bytestring = "0.1.5"
derive_more = "0.99.5"
either = "1.5.3"
futures = "0.3.12"
ahash = "0.6.2"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
pin-project-lite = "0.2.4"

[dev-dependencies]
env_logger = "0.8"

rustls = "0.19"
ntex = { version = "0.2.0", features = ["rustls"] }

[patch.crates-io]
ntex = { git = "https://github.com/ntex-rs/ntex.git" }